# Generated by Django 5.1 on 2024-08-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DwUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('hwid', models.TextField(null=True)),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('MANAGER', 'MANAGER'), ('BETA', 'BETA'), ('USER', 'USER'), ('MEDIA', 'MEDIA'), ('VISITOR', 'VISITOR'), ('DEACTIVATED', 'AZIK')], default='USER', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
