# Generated by Django 5.0.4 on 2024-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwuser',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('MANAGER', 'MANAGER'), ('BETA', 'BETA'), ('USER', 'USER'), ('MEDIA', 'MEDIA'), ('VISITOR', 'VISITOR'), ('DEACTIVATED', 'AZIK')], default='USER', max_length=50),
        ),
    ]
