# Generated by Django 5.0.4 on 2024-04-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_dwuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dwuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='dwuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='dwuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='dwuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dwuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dwuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='dwuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dwuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='dwuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='dwuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dwuser',
            name='user_permissions',
        ),
    ]
