# Generated by Django 5.1 on 2024-08-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
    ]
