# Generated by Django 5.1 on 2024-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0002_alter_statistics_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferalsystem',
            name='refferalBonus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='refferalsystem',
            name='refferalNumber',
            field=models.IntegerField(null=True),
        ),
    ]
