# Generated by Django 5.1 on 2024-08-22 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subType', models.IntegerField(choices=[('MONTH', 30), ('THREE_MONTHS', 90), ('YEAR', 364), ('NONE', 0)], default=0)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('sxpirationDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
