# Generated by Django 5.1 on 2024-08-23 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subType', models.IntegerField(choices=[('MONTH', 30), ('THREE_MONTHS', 90), ('YEAR', 364), ('NONE', 0)], default=0)),
                ('startDate', models.DateTimeField(default=None, null=True)),
                ('expirationDate', models.DateTimeField(default=None, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
