name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}):$(date +%s)
    
    - name: Tag the image to latest
      run: docker tag ${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}):$(date +%s) ${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}):latest
      
    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      
    - name: Push the image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}):$(date +%s)
        docker push ${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}):latest
