name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker tag
      run: |
        IMAGE_TAG=${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}):$(date +%s)
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}):$(date +%s)
    
    - name: Tag the image to latest
      run: docker tag $IMAGE_TAG ${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}):latest
      
    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      
    - name: Push the image to Docker Hub
      run: |
        docker push $IMAGE_TAG
        docker push ${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}):latest
