name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker tag
      run: |
        echo "IMAGE_TAG=${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}:$(date +%s)" >> $GITHUB_ENV
        echo "LATEST_TAG=${{ secrets.DOCKER_USER }}/${{ secrets.REPOSITORY_NAME }}:latest" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}
    
    - name: Tag the image as latest
      run: docker tag ${{ env.IMAGE_TAG }} ${{ env.LATEST_TAG }}
      
    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      
    - name: Push the image to Docker Hub
      run: |
        docker push ${{ env.IMAGE_TAG }}
        docker push ${{ env.LATEST_TAG }}
