name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Установка переменных окружения для тэга
      run: |
        # Формируем имя для APP_NAME, убираем все лишние символы кроме допустимых
        APP_NAME="${{ secrets.DOCKER_USER }}/$(echo ${{ secrets.REPOSITORY_NAME }}
        echo "$APP_NAME" > APP_NAME
        echo "$GITHUB_SHA" > TAG 
        
    - name: Вывод значений APP_NAME и TAG для отладки
      run: |
        echo "APP_NAME=$(cat APP_NAME)"
        echo "TAG=$(cat TAG)"
      
    - name: Сборка Docker образа
      run: docker build . --file Dockerfile --tag $(cat APP_NAME):$(cat TAG)
    
    - name: Тэгирование образа как latest
      run: docker tag $(cat APP_NAME):$(cat TAG) $(cat APP_NAME):latest
      
    - name: Логин в Docker
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Пуш Docker образа
      run: docker push $(cat APP_NAME):latest
